/*
Code generated by automapper-gen. DO NOT EDIT.
Learn more: https://git.weirdcat.su/weirdcat/automapper-gen
*/

package dtos

import (
	"errors"
	"fmt"
	db "git.weirdcat.su/weirdcat/automapper-gen/example/db"
	"sync"
	"time"
)

// Converter type for type-safe conversions
type Converter[From any, To any] func(From) (To, error)

// Global converter registry (thread-safe)
var converters = make(map[string]any)
var convertersMu sync.RWMutex

// RegisterConverter registers a type-safe converter
func RegisterConverter[From any, To any](name string, fn Converter[From, To]) {
	convertersMu.Lock()
	defer convertersMu.Unlock()
	converters[name] = fn
}

// Convert performs a type-safe conversion using a registered converter
func Convert[From any, To any](name string, value From) (To, error) {
	var zero To
	convertersMu.RLock()
	converterIface, ok := converters[name]
	convertersMu.RUnlock()
	if !ok {
		return zero, fmt.Errorf("converter %s not registered", name)
	}
	converter, ok := converterIface.(Converter[From, To])
	if !ok {
		return zero, fmt.Errorf("converter %s has wrong type", name)
	}
	return converter(value)
}

func init() {
	RegisterConverter("TimeToString", TimeToJSString)
	RegisterConverter("RoleEnum", StrRoleToEnum)
	RegisterConverter("InterestEnums", StrInterestsToEnums)
}

// TimeToJSString converts time.Time to JavaScript ISO 8601 string
func TimeToJSString(t time.Time) (string, error) {
	return t.Format(time.RFC3339), nil
}

// MapFromUserDB maps from db.UserDB to UserDTO
func (d *UserDTO) MapFromUserDB(src *db.UserDB) error {
	if src == nil {
		return errors.New("source is nil")
	}

	d.ID = src.ID
	d.Username = src.Username
	{
		var err error
		d.Role, err = Convert[string, Role]("RoleEnum", src.Role)
		if err != nil {
			return fmt.Errorf("converting field Role: %w", err)
		}
	}
	if src.About != nil {
		d.About = *src.About
	}
	// About: nil pointer will result in zero value
	{
		d.Pets = make([]PetDTO, len(src.Pets))
		for i, item := range src.Pets {
			if err := d.Pets[i].MapFromPetDB(&item); err != nil {
				return fmt.Errorf("mapping nested field Pets[%d]: %w", i, err)
			}
		}
	}
	// FeaturedAchievement: not found in source, will be zero value
	{
		var err error
		d.Interests, err = Convert[[]string, []Interest]("InterestEnums", src.Interests)
		if err != nil {
			return fmt.Errorf("converting field Interests: %w", err)
		}
	}
	if src.Birthday != nil {
		var err error
		var result string
		result, err = Convert[time.Time, string]("TimeToString", *src.Birthday)
		if err != nil {
			return fmt.Errorf("converting field Birthday: %w", err)
		}
		d.Birthday = &result
	}
	// Birthday: nil pointer will result in nil
	{
		var err error
		d.CreatedAt, err = Convert[time.Time, string]("TimeToString", src.CreatedAt)
		if err != nil {
			return fmt.Errorf("converting field CreatedAt: %w", err)
		}
	}

	return nil
}

// MapFromPetDB maps from db.PetDB to PetDTO
func (d *PetDTO) MapFromPetDB(src *db.PetDB) error {
	if src == nil {
		return errors.New("source is nil")
	}

	d.ID = src.ID
	d.Name = src.Name
	{
		var err error
		d.Interests, err = Convert[[]string, []Interest]("InterestEnums", src.Interests)
		if err != nil {
			return fmt.Errorf("converting field Interests: %w", err)
		}
	}
	if src.Birthday != nil {
		var err error
		var result string
		result, err = Convert[time.Time, string]("TimeToString", *src.Birthday)
		if err != nil {
			return fmt.Errorf("converting field Birthday: %w", err)
		}
		d.Birthday = &result
	}
	// Birthday: nil pointer will result in nil
	{
		var err error
		d.CreatedAt, err = Convert[time.Time, string]("TimeToString", src.CreatedAt)
		if err != nil {
			return fmt.Errorf("converting field CreatedAt: %w", err)
		}
	}

	return nil
}

// MapFromAchievementDB maps from db.AchievementDB to AchievementDTO
func (d *AchievementDTO) MapFromAchievementDB(src *db.AchievementDB) error {
	if src == nil {
		return errors.New("source is nil")
	}

	d.ID = src.ID
	d.Title = src.Title
	d.Description = src.Description
	{
		var err error
		d.CreatedAt, err = Convert[time.Time, string]("TimeToString", src.CreatedAt)
		if err != nil {
			return fmt.Errorf("converting field CreatedAt: %w", err)
		}
	}

	return nil
}
