/*
Code generated by automapper-gen. DO NOT EDIT.
Learn more: https://git.weirdcat.su/weirdcat/automapper-gen
*/

package dtos

import (
	"errors"
	"fmt"
	db "git.weirdcat.su/weirdcat/automapper-gen/example/db"
)

// MapFromUserDB maps from db.UserDB to UserDTO
func (d *UserDTO) MapFromUserDB(src *db.UserDB) error {
	if src == nil {
		return errors.New("source is nil")
	}

	d.ID = src.ID
	d.Username = src.Username
	{
		var err error
		d.Role, err = StrRoleToEnum(src.Role)
		if err != nil {
			return fmt.Errorf("converting field Role: %w", err)
		}
	}
	if src.About != nil {
		d.About = *src.About
	}
	// About: nil pointer will result in zero value
	{
		d.Pets = make([]PetDTO, len(src.Pets))
		for i, item := range src.Pets {
			var err error
			err = d.Pets[i].MapFromPetDB(&item)
			if err != nil {
				return fmt.Errorf("mapping nested field Pets[%d]: %w", i, err)
			}
		}
	}
	if src.FeaturedAchievement != nil {
		var nested AchievementDTO
		var err error
		err = nested.MapFromAchievementDB(src.FeaturedAchievement)
		if err != nil {
			return fmt.Errorf("mapping nested field FeaturedAchievement: %w", err)
		}
		d.FeaturedAchievement = nested
	}
	// FeaturedAchievement: nil pointer will result in zero value
	{
		var err error
		d.Interests, err = StrInterestsToEnums(src.Interests)
		if err != nil {
			return fmt.Errorf("converting field Interests: %w", err)
		}
	}
	if src.Birthday != nil {
		result := TimeToString(*src.Birthday)
		d.Birthday = &result
	}
	// Birthday: nil pointer will result in nil
	d.CreatedAt = TimeToString(src.CreatedAt)

	return nil
}

// MapToUserDB maps from UserDTO to db.UserDB
// Ignored fields: Role, Pets, FeaturedAchievement, Interests
func (d *UserDTO) MapToUserDB(dst *db.UserDB) error {
	if dst == nil {
		return errors.New("destination is nil")
	}

	dst.ID = d.ID
	dst.Username = d.Username
	// Role: converter has no inverter, skipped
	{
		v := d.About
		dst.About = &v
	}
	// Pets: nested DTO mapping not supported in MapTo, skipped
	// FeaturedAchievement: nested DTO mapping not implemented in MapTo, skipped
	// Interests: converter has no inverter, skipped
	if d.Birthday != nil {
		// FIXME: Generated output uses unimported library:
		// var result time.Time
		// var err error
		// result, err = StringToTime(*d.Birthday)
		// if err != nil {
		// 	return fmt.Errorf("converting field Birthday: %w", err)
		// }
		{
			result, err := StringToTime(*d.Birthday)
			if err != nil {
				return fmt.Errorf("converting field Birthday: %w", err)
			}
			dst.Birthday = &result
		}
	}
	// Birthday: nil pointer will result in nil
	{
		var err error
		dst.CreatedAt, err = StringToTime(d.CreatedAt)
		if err != nil {
			return fmt.Errorf("converting field CreatedAt: %w", err)
		}
	}

	return nil
}

// MapFromPetDB maps from db.PetDB to PetDTO
func (d *PetDTO) MapFromPetDB(src *db.PetDB) error {
	if src == nil {
		return errors.New("source is nil")
	}

	d.ID = src.ID
	d.Name = src.Name
	{
		var err error
		d.Interests, err = StrInterestsToEnums(src.Interests)
		if err != nil {
			return fmt.Errorf("converting field Interests: %w", err)
		}
	}
	if src.Birthday != nil {
		result := TimeToString(*src.Birthday)
		d.Birthday = &result
	}
	// Birthday: nil pointer will result in nil
	d.CreatedAt = TimeToString(src.CreatedAt)

	return nil
}

// MapFromAchievementDB maps from db.AchievementDB to AchievementDTO
func (d *AchievementDTO) MapFromAchievementDB(src *db.AchievementDB) error {
	if src == nil {
		return errors.New("source is nil")
	}

	d.ID = src.ID
	d.Title = src.Title
	d.Description = ToLower(src.Description)

	return nil
}

// MapToAchievementDB maps from AchievementDTO to db.AchievementDB
// Ignored fields: Description
func (d *AchievementDTO) MapToAchievementDB(dst *db.AchievementDB) error {
	if dst == nil {
		return errors.New("destination is nil")
	}

	dst.ID = d.ID
	dst.Title = d.Title
	// Description: converter has no inverter, skipped

	return nil
}
