// Code generated by automapper-gen. DO NOT EDIT.

package dtos

import (
	"errors"
	"fmt"
	"time"
	"git.weirdcat.su/weirdcat/automapper-gen/example/db"
)

// Converter type for type-safe conversions
type Converter[From any, To any] func(From) (To, error)

// Global converter registry
var converters = make(map[string]interface{})

// RegisterConverter registers a type-safe converter
func RegisterConverter[From any, To any](name string, fn Converter[From, To]) {
	converters[name] = fn
}

// Convert performs a type-safe conversion using a registered converter
func Convert[From any, To any](name string, value From) (To, error) {
	var zero To
	converterIface, ok := converters[name]
	if !ok {
		return zero, fmt.Errorf("converter %s not registered", name)
	}
	converter, ok := converterIface.(Converter[From, To])
	if !ok {
		return zero, fmt.Errorf("converter %s has wrong type", name)
	}
	return converter(value)
}

func init() {
	// Register TimeToString: time.Time -> string
	RegisterConverter[time.Time, string]("TimeToString", TimeToJSString)
}

// TimeToJSString converts time.Time to JavaScript ISO 8601 string
func TimeToJSString(t time.Time) (string, error) {
	return t.Format(time.RFC3339), nil
}

// MapFromUserDB maps from db.UserDB to UserDTO
func (d *UserDTO) MapFromUserDB(src *db.UserDB) error {
	if src == nil {
		return errors.New("source is nil")
	}

	d.ID = src.ID
	d.Username = src.Username
	{
		var err error
		d.CreatedAt, err = Convert[time.Time, string]("jsTime", src.CreatedAt)
		if err != nil {
			return fmt.Errorf("converting field CreatedAt: %w", err)
		}
	}

	return nil
}

